baseURL = 'https://andreispurim.github.io/latlander/'
title = 'The Latlander'
publishDir = 'docs'

disablePathToLower = false
enableGitInfo = false

[markup]
[markup.goldmark.renderer]
  unsafe = true

[params]
  BookTheme = 'light'
  BookToC = false
  BookSection = 'docs'
  BookSearch = true
  BookComments = false
  BookPortableLinks = false
  BookServiceWorker = false
